---
title: "General Framework for Seat Occupancy Expectation"
author:
  name: "Fukumoto Tomoya"
  affiliation: "Operation Planning"
date: "2018-08-20"
output: html_document
#abstract: "hogehoge is important issue for us. We established a mathematical framework to expect seat occupancy of ride attractions. Our model is based on Markov chain model. Since our model is general, we can aplly to any attraction."
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Introduction
One of the most important issue for park operation is raising guestcounts of attractions.
Since guestcounts can be decomposed by dispatch count and seat occupancy, we focus on these two numbers.
The aim of this study is to establish a mathematical framework to expect seat occupancy of ride attractions.
We revealed that seat occupancy is derivable by statistics of group size of arrival guests, the number of seats, queue formation and grouping strategy.
This framework will help us to optimize queue formation and grouping strategy.
Because the model is general, that is, the model is not dependent on any actual attraction, the framework can be applied to every attractions.

## Modeling and Framework
### Overview
For ride attractions, grouping operation is deeply related to seat occupancy.
Crew create a group to dispatch from arrival guests not to break each group of guests.
Thus if a group size of arrival guest is note suited, crew can not make seat full however efficient they are.
This indicates the existence of upper bound of seat occupancy in each attractions.

The upper bound would depend on statistics of group size of arrival guest and the number of seats for a vehicle.
With the value, it could be possible to clarify the efficiency of grouping operation and whether seat occupancy can improve or not.
In addition we will be able to judge if a new operation can achieve more seat occupnacy.

The upper bound can be probability variable because arrivals of guest should be probabilistic.
Thus we have to estimate upper bounds as expectation values.  

### Model
To evaluate the upper bound, we define some operational situations by probabilistic model as below

- the size of $i$th arrival group is probability variable $x_i$.
- the number of seats filled with persons is a probability variable $a_i$ after the $i$the group have seats.

And we assume that

- the probability that a group sized $k$ arrives is time stationary and $p[x_i=k]=p_k$ .

We use **Markov chain model** to solve this problem.
Markov chain model is a stochastic model using state and transition.

We set $a_i$ as a state after $i$ times transitions.
State of Markov chain 

Arrival probability and grouping strategy decide a transition matrix of Markov chain.  

### Solution
Steps to Solve a Problem is

1. Set a transition matrix $T$. 
2. Find the stationary state as a solution of equation $Tx=x$.
3. Calculate expectation value of occupancy.

## Example: Single Grouping
We calculate seat occupancy 

- we make only one line of seats
- 4 seats on the line

We imagined an attraction like Harry Potter and the Forbidden Journey.

### Transition Matrix 
If we make only one line, we have to group guests in arrival order.
Thus our grouping strategy can be decided automatically.
$$
T=\begin{pmatrix}
  p_4 & p_3+p_4& p_2+p_4&p_1+p_4\\
  p_1&0&0&0\\
  p_2&p_1&0&p_2\\
  p_3&p_2&p_1+p_3&p_3
  \end{pmatrix}
$$
 
### Single Queue   

To approach this problem, we assume $p_1=p, p_2=p_3=p_4=q/3$.
This is the simplest model which has only two parameters, single guest ratio and grouped guest.
And each grouped guests come to an attraction in the same possibility.
Then by an equation $Tx=x$, we can obtain the stationary state
$$
x = \frac{1}{6(p+1)(2p^2-p+2)}\begin{pmatrix}
  2p^2+2p+5\\
  2p^3+2p^2+5p\\
  4p^3+4p^2-2p+3\\
  6p^3-2p^2+p+4
  \end{pmatrix}
$$

The probability of dispatch
$$
p_D=\frac{-28p^4+24p^3+6p^2-8p+33}{18(p+1)(2p^2-p+2)}
$$

Expected occupancy
$$
\begin{eqnarray}
\mathrm E[Ocp] &=& \frac{1}{p_D}\frac{3-2p}{4}\\
  &=& \frac{9(p+1)(3-2p)(2p^2-p+2)}{2(-28p^4+24p^3+6p^2-8p+33)}
  \end{eqnarray}
$$


We substitute concrete values to the parameters.
In case of $p=1/20$, 
$$
\pi = \begin{pmatrix}\pi_0\\\pi_1\\\pi_2\\\pi_3\end{pmatrix}= \begin{pmatrix}0.415\\ 0.021\\ 0.236\\ 0.329\end{pmatrix}
$$
and dispatch transition is
$$
T_D = \begin{pmatrix}
  p_4&p_3+2p_4&p_2+2p_4&p_1+2p_4\\
  0&0&0&0\\
  0&0&0&p_2\\\
  0&0&p_3&p_3
  \end{pmatrix}
$$
thus
$$
p_D = \mathbf 1^\mathrm{T}T\pi=0.8827
$$
Then we obtain the expected occupancy is 
$$
\mathrm E[Ocp] = \begin{pmatrix}
  p_4&p_3+\frac54p_4&p_2+\frac12p_3+\frac32p_4&p_1+\frac34p_2+\frac34p_3+\frac74p_4\\
\end{pmatrix}\begin{pmatrix}\pi_0\\\pi_1\\\pi_2\\\pi_3\end{pmatrix}
  =0.8213
$$

### With Single Rider Queue
If we have a single rider queue, the parameters should be modified as
$$
p_1=0, p_2=p_3=p_4=1/3
$$
Then we can obtain the stationary state as
$$
\pi=\begin{pmatrix}0.417\\0\\0.25\\0.333\end{pmatrix}
$$
Using this, we can easily calculate dispatch probability
$$
D = 0.9167
$$
and the expectation of occupancy
$$
\mathrm E[Ocp]=0.818
$$
Finaly, we adjust a single rider effect as 
$$
\mathrm E[Ocp_S]=\mathrm E[Ocp](1+p_s)=0.859
$$
where $p_s$ is a single rider availability assumed by 0.05.

### Pre-grouping
- we separate guests by its group size (2,4) and 3 before grouping

If group size is only 3, expected occupancy will be 0.75.

In case of group size 2 or 4, we set each probability as $p, 1-p$.

Transition matrix
$$
T = \begin{pmatrix} 1-p&1\\p&0\end{pmatrix}
$$

Stationary state
$$
\pi = \frac{1}{1+p}\begin{pmatrix}1\\p\end{pmatrix}
$$

Expected Dispatch
$$
\mathrm E[D]=\frac{-p^2+p+1}{p+1}
$$

Expected Occupancy
$$
\mathrm E[Ocp]=\frac{p^2-p+2}{2(-p^2+p+1)}
$$
In case $p=1/2$, expected occupancy is minimum 0.9.


## Conclusion
- change 
