---
title: "研究計画書"
author:
  name: "福本 知也"
date: "2024-03-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## 研究名
不確実性のある環境下で、複雑な制約があるオンラインパッキング問題。
またその不確実性を条件付きで制御できる場合の最適化問題。

## 背景
人が順次やってきて、彼らに座席を提供するものとする。
座席には列があり、一つの列に座れる人数には制限がある。
人はグループでやってくる。
同じグループの人には同一の列で連結した席を提供しなければならない。
人がやってきた順番に席を提供しなければならない。
次にやってくるグループの大きさを知ることはできず確率的に定まるものとする。

空席をできる限り少なくして多くの人に座席を提供したい。

### 背景の具体的なイメージ
遊園地の乗り物で座席を提供する戦略

## 問題
２つ問題がある。

1つ目の問題はある空席状態に対してあるグループサイズがやってきたときに、どの列を着席する列として指定するかという戦略を定めることである。
戦略から期待される満席率(期待着席数/提供席数)を評価し、最も期待される満席率が高い戦略を採用したい。

2つ目の問題は事前にグループサイズを分別できるとすれば、どのような分別ルールが満席率を最も高めるかを決定することである。
同じ設備が複数ある場合、事前にグループサイズによってどちらの設備へ案内するかをふるい分けることができる。
つまり制限付きでやってくるグループの不確実性を減少させることができる。
そのときどのようなパターンでふるい分けるのが満席率を高めるかを決定したい。
この問題は１つ目の問題が解決した後でなければ解くことができない。

どちらも問題としては一つの列に座れる人数とグループサイズの統計が入力となり、出力として満席率がありこれを最も高くする行動戦略を決定するものである。
またグループサイズの分布は固定的なものでないため戦略はグループサイズの統計に関してロバスト性を持つのが望ましい。
また季節や時間の流れによっても変化するため、環境の変化に追従するよう戦略を変更するメタ戦略も見つけたい。

## 事前研究
グループサイズの統計が独立同一な多項分布で座席の列が一列しかない場合は、マルコフ過程モデルを用いて期待満席率を計算することができる。
なぜならばやってくるグループをどの列に着席させるかという自由度が存在しないためである。
この場合は第１の問題は満席率の計算のみになる。
マルコフ過程の状態数は一列の席数+1で、状態間の遷移確率はグループサイズの統計によって定まる。
満席率の計算ができれば第２の問題も解決することができる。

一列あたり席数４の場合（現実の条件）で一般的なグループサイズの統計パラメータについて満席率の期待値を計算することができた。
シングルライダーという一人グループ専用のキューを設置したときにどの程度満席率が改善するのかを計算した。
２つ目の問題として事前にグループサイズを分割するときにどのパターンが最も満席率を改善するかを計算した。

詳細は別ファイル(事前研究)

## 研究方針
実際には、座席の列数が１列で１列５席の場合にも事前研究と同様の知識が欲しい。
必要な条件が現れるたびに毎回解析をせずに済むように、任意の一列の席数条件について主張できる結果が存在しないか研究したい。

列数が２以上の場合は、どの列に案内するかの自由度が存在するためマルコフ過程で期待満席率を計算できない。
グループサイズの統計を独立同一な多項分布とすれば動的計画法で最適解を見つけることができるか？

グループサイズの統計は実績から推測できるだけなので正確な情報は得られない。
よって戦略は最適であるだけでなくグループサイズの統計に対してロバストであることが望ましい。

実際に運用できる戦略はある程度シンプルである必要がある。
どうやってシンプルな解を見つけるか、そもそもシンプルさの制約をどのように入れるか。

最も望ましいのは環境の変化に自動的に追従するメタ戦略を見つけることである。
強化学習による解析は可能だろうか？
